### ISSUE TITLE
Use case: facilitate sharing of basic data about public events

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/Core-Public-Event-Vocabulary#1]
Information sharing across organisations is often hampered by the lack of semantic agreements.  Common data standards, such as Core Vocabularies, help public administrations to overcome the semantic barrier to information sharing. The Core Public Event Vocabulary is designed to make the exchange of basic information about public events easier. By using the vocabulary, administrations publishing data about their events will enable
- easier discovery of their event within and between countries;
- improved understanding of provided information because of common definitions; and
- easier comparison of similar events across sectors or countries.

**Comment by cultureMatters** [comment]
I totally agree. Having read the Use Cases of the Core Public Service Vocabulary specification V0.07(D5.1.2), I 'd add the following : 
_The use of a Structured Vocabulary is the first stage of Requirement Analysis, as imposed by the Science of Informatics. It  mainly consists of words for basic entities  that interact and function within the System under analysis. The vocabulary supports the formal description before the System gets transformed into a Diagram. Therefore, it is important to specify the concrete Data that need to be definitely articulated. The description via Use Cases follows or precedes the Vocabulary. Thus defining the main Core Entities after reading the Use Cases is the key process. 
The Public service class , the input / output class and the Rule Class referred/contained in the Document are very well defined, and can be easily handled as a fine basis for object Oriented pseudo-code. Let's enrich and develop them in detail._

**Comment by EmidioStani** [comment]
In order to make the easier discovery the proposal is:

1) associate an Address to the Event, so it is possible to discover similar events with the same address
2) add "topic" property to the Event, so it is possible to discover similar events with the same topic

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to: 
- Add the "address" relation to (Core Location) Address class for physical location.
- Keep the "format" (Code) property to specify the format of the event.
- Keep the "accessibility" (Text) property.
- Not enforce cardinalities, so there can be multiple locations for an event.
