### ISSUE TITLE
Definition of place

### ISSUE THREAD

**Issue by fvepwc** [SEMICeu/Core-Public-Event-Vocabulary#10]
During the last webinar, there was a discussion on how a Place should be defined. This is what was said during the webinar: 

- Place: how should we define a place? For now, we have that it must be a physical or virtual location.
- Apparently there is something on schema.org concerning virtual locations, but no link was sent.
- For physical location the geolocation is crucial (for many use cases).
- There is an existing class for physical locations: dct:Location.
- For online only events, see also https://github.com/schemaorg/schemaorg/issues/1842 

Further discussions on this can be held here.

**Comment by CharlineAlexandre** [comment]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
During the discussions, there have been comments made on the re-use of Core Location in CPEV. It was said that Core Location should be used, and more properties should be brought such as:
- Difference between physical and virtual location
- Accessibility of a location
- Multiple locations for a single event

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to:

1) link to (Core Location) Address class for physical location
2) specify the format of the event, by keeping the property "format"
3) keep the property "accessibility"
4) like for other Core Vocabularies, cardinalities are not enforced, so there can be multiple location for an event

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to: 
- Add the "address" relation to (Core Location) Address class for physical location.
- Keep the "format" (Code) property to specify the format of the event.
- Keep the "accessibility" (Text) property.
- Not enforce cardinalities, so there can be multiple locations for an event.
