### ISSUE TITLE
Reliance on schema.org

### ISSUE THREAD

**Issue by fvepwc** [SEMICeu/Core-Public-Event-Vocabulary#11]
During the last webinar, there was a discussion on the dependency on schema.org. Below we repeat the main points of the discussion:

There are a lot of dependencies on schema.org, but there is no involvement in the management of the vocabulary. What happens if schema.org goes another way?
- Indeed strong reliance on schema.org, which comes from the use cases in earlier webinars.
- Google has every intention to keep this alive.
- You could take everything in cv, at least then you can guarantee stability.
- There is no huge risk to go with schema.org for now, we can always change later. It’s good for the use cases and for promotional visibility.

This is indeed a fundamental discussion, which we can continue here

**Comment by rtroncy** [comment]
I would also +1 for those arguments but I mainly want to clarify a number of incorrect statements above. First, schema.org is different than Google! Please, refer the governance board of schema.org, which includes representatives of 4 main search engines + other consultants. This is embraced by a community that goes well beyond. Google, as a dominant search engine (in the Western world), has indeed the highest interest but this is an orthogonal issue. Schema.org has now a process to deprecate terms from the vocabulary but so far, the guiding principle has to be as much as possible backward compatible when proposing schema evolutions. Therefore, I don't see a high risk in developing a vocab that is deeply tangled with schema.org, all the contrary.

**Comment by marc-portier** [comment]
Who controls any vocabulary should really not be of concern. Even worse: making an observation or case about why it should largely flags the makers are not to be trusted to control one themselves?

After all "cool uri's don't change". Extending that to semantic uri's suggests we do not (ever) alter their semantics after being made public.

We should guarantee longevity of our own work. Equally we should be able to assume the same from other work we depend upon. 

IMHO this is just the only correct way of doing it. If we fail to fit into this new global & eternal way of describing our data, than the whole effort is in vain and today's open linked data efforts are not stepping up to their promise: just another layer on top of the existing pile of historic attempts to let data and its meaning surpass the entanglements of local politics and claimed intellectual property.

**Comment by akuckartz** [comment]
Ideally there should be some documented best practice criteria applied consistently to such dependencies.

**Comment by EmidioStani** [comment]
Mapping with schema.org will be considered whenever meaning of the concepts will be equivalent.
