### ISSUE TITLE
use of schema:Place and events online

### ISSUE THREAD

**Issue by pwin** [SEMICeu/Core-Public-Event-Vocabulary#15]
In the core Location Vocab dcterms:Location is used.  In CPEV this is being modelled as schema:Place to cater for the possibility that some events are online.  I think that being online is location-independent and non-specific about location, but it is specific about channel.  I think that CPEV should be using similar approaches to CPSV-AP where services can be provided at a location or through a channel in a location-independent way.  The issue is that by using schema:Place we are mixing up a very person-centred idea of place (where 'I' am now) with a more objective and fixed idea of place.  I think we should split these and use 'channel' for the online events

**Comment by EmidioStani** [comment]
Proposal to:

1) add relation "address" to link Public Event to (Core Location) "Address" class, detailing the physical location of the Event
2) keep the "format" property indicating the classification how the event is arranged e.g.  conference call and physical meeting

This simplicity should be enough to express the how an event is arranged in contrast to CPSV-AP which is an application profile requiring a certain level of complexity.

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to: 
- Add the "address" relation to (Core Location) Address class for physical location.
- Keep the "format" (Code) property to specify the format of the event.
- Keep the "accessibility" (Text) property.
- Not enforce cardinalities, so there can be multiple locations for an event.
