### ISSUE TITLE
Hierarchy in events

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#16]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
The fact that events can sometimes have a parent and / or a child relationship was discussed. In the same vein, an event could be part of a series of events.

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to:

1) keep the relation "subEvent" to another Event encompassing the first one
2) add the relation "parentEvent" to another Event included in the first one

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to keep subEvent and add parentEvent relation.
