### ISSUE TITLE
Frequency of events

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#18]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
The frequency of events was discussed. Indeed, there are recurrent events for which, frequency is an important aspect.

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Frequency is dealt in issue https://github.com/SEMICeu/Core-Public-Event-Vocabulary/issues/20

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to: 
- Use TemporalEntity.
- Add description and frequency property to TemporalEntity.
- Add hasNextEvent and hasPreviousEvent.
