### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#19]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
Tickets were discussed. Tickets relate to pricing, a maximum capacity, amongst others. Tickets price might be considered as too granular for the core model because of the many exceptions that exist (e.g., elders, children, families...). Based on our existing knowledge on how public organizations are functioning on the way that they are handling events, we believe that such information is not needed.

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to remove Offer and Ticket classes, as requirements are not defined

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to remove Ticket and Offer classes.
