### ISSUE TITLE
Use case: publication of event data as Linked Open Data

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/Core-Public-Event-Vocabulary#2]
The Core Public Event Vocabulary aspires to support the use case of publishing event data as Linked Open Data. Therefore, the vocabulary would need to be expressed in RDF and its classes and properties should be identified using persistent URIs.

**Comment by akuckartz** [comment]
:+1:

**Comment by EmidioStani** [comment]
Like for other Core Vocabularies, the artefacts generated for Core Public Event will include RDF serialization
