### ISSUE TITLE
Contact Point

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#21]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
It was discussed that contact point, already defined in [CPOV](https://github.com/SEMICeu/CPOV), should be reused as part of CPEV.

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to reuse ContactPoint from CPOV

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to reuse ContactPoint from CPOV and add relation with PublicEvent:
- Option:use TemporalEntity to clarify contact times.
