### ISSUE TITLE
Identification of events

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#22]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
Several points regarding the identification of events have been raised and new attributes were suggested:
- Title of the event
- Topics; allowing to specify the domain / area of the event and to link the event to other events

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to:

- keep title (Text) property: to indicate the name given to the event
- add topic (Code) property: to indicate the main subjects of the event
- add identifier (Literal) property: to distinguish univoquely an event from another

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Keep title, add identifier (Literal) and topic (code).
- Consider initial keywords for the topic property.
- Consider the properties: language and meetingType.
