### ISSUE TITLE
Change license to CC BY 4.0

### ISSUE THREAD

**Issue by sandervd** [SEMICeu/Core-Public-Event-Vocabulary#23]
See discussion https://github.com/SEMICeu/CPSV-AP/issues/38

and consistent with https://github.com/SEMICeu/Core-Person-Vocabulary/commit/410045148a8f9b95ee1a099e9d8675e7d34ea541

**Comment by EmidioStani** [comment]
Like for other Core Vocabularies the proposal is to change to CC BY 4.0

**Comment by EmidioStani** [comment]
The license has been updated to CC-BY
