### ISSUE TITLE
Non-public events

### ISSUE THREAD

**Issue by akuckartz** [SEMICeu/Core-Public-Event-Vocabulary#4]
The readme suggests that the scope is restricted to "public" events. I propose to remove this restriction.

**Comment by cultureMatters** [comment]
In my opinion, the "public" events are ruled by _totally different methodologies_ from "non-public" events; they serve and address **the whole of** society or state, whereas non-public/private events belong to a restricted set of people with a specific goal. Thus, I will disagree with akuckartz, that NOT meaning that private events cannot use parts of the Core Public Event Vocabulary.

**Comment by CharlineAlexandre** [comment]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV. There was a discussion as to what should be the scope of public events. 
Another point discussed is the definition of Events. The point raised was to have examples of Events that would help clarify the context and the usage of the Core Public Event Vocabulary. As an example, a conference or a procurement event could be added.
Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
The proposal is to keep the concept  "public event" in alignment with the definition provided of Publication Office:
_The public event type table defines public events that happen at a particular place and time, are organised by an agent for a particular purpose, and are of interest to a general audience._ 

Examples of Public Events will be added later on within the specification.

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Collect further comments and suggestions on the definition of PublicEvent
- Look at the definition by CIDOC CRM.
