### ISSUE TITLE
possible Use Case (please add feedback)

### ISSUE THREAD

**Issue by cultureMatters** [SEMICeu/Core-Public-Event-Vocabulary#5]
USE CASE : Adding **“relative information”** metadata

I aim to attend the HPC [= High Performance Computing] event that is being realised by GRNET. Unfortunately, I have had very little experience on the subject of high Computing, that consists of handling several processors -nodes- simultaneously ; I've had only the knowledge acquired from my master diploma entitled “High Performance Algorithms”. In spite of this lack of experience, I realised - by surfing on the internet- that there exists a  blog referring to the same title. The title of the event may exist on the web as part of a blog or as a wiki entry, thus forming the “relative info to the subject” information, usually being a url (in the specific example: http://www.hpcnotes.com/p/hpc-events.html). So, when forming the event metadata, a  “relative info” can be held as well. 

The event itself may correspond to a  _Uniform Resource Locator_ -(URL)- that depicts all data concerning the event (i.e. sponsors, time, place/Venue) and this can be also considered important information of the event, as defined on the Slides (Information Requirements);  I think  that“relative info” is another field that belongs to the metadata information of the Event.

Thank you.
D.P.

**Comment by rtroncy** [comment]
+1 for this use case. It is often implemented using the [rdfs:seeAlso](https://www.w3.org/TR/rdf-schema/#ch_seealso) property which is a built-in construct in the RDF model.

**Comment by fragou** [comment]
Deal all
I would like to ask for consideration  the following attributes (whether or not may be useful):
a) the mean(s) that an event takes place / trasmission (for example requires physical presence, via teleconference) as well as similtaneous ways of monitoring 
(such as live broadcasting)
b)publicity means/promotion (such as internet, posters etc)
c) whether it requires registration
d) whether it requires accomodation (related with duration feature)

For example European Parliament yesterday perfomed a live bloadcast
LIVE from Strasbourg: the leader of the International Campaign to Abolish Nuclear Weapons, which won last year's Nobel Peace Prize, discusses how to rid the world of the continuing risk of nuclear weapons.
accessible via facebook

Thank you
Pavlina Fragkou

**Comment by cultureMatters** [comment]
Hi all. Maybe it is important to add also an **Edition** of the event; for example on 21th of February the 4th Congress of ICT (Information & Communication Technology) Security World will take place in Athens. The number 4 indicates the 4th presence of the Event with _identical scope_. Sorry if it is already referred... I look forward to reading the first general model created!

**Comment by EmidioStani** [comment]
Proposal to:

1) replace the property "url" with the property "homepage" to indicate the main page, URL of the Public Event where information may be found;
2) add the property "registration" to indicate the page that provides means to attend the Public Event;
3) add the property "eventNumber" to indicate the sequence position of the Public Event.

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Keep description.
- Replace url (URI) with homepage (Document).
- Keep registration (Document).
- Add eventNumber.
