### ISSUE TITLE
Class EventDescription

### ISSUE THREAD

**Issue by fvepwc** [SEMICeu/Core-Public-Event-Vocabulary#8]
During the last webinar, there was a discussion on whether a class EventDescription is needed. This is what was said on this in the webinar:

- Add a class EventDescription since the description is often a structured text; it can be formatted, in several languages, can be a poster.
- Whether an event has a specific description can also be a way to distinguish between complex events or subevents.
- We could probably just link up with existing generic web-content-models (like Dublin Core). They have their own model and just link to the event they are about.
- Dublin Core will not be enough if you want to express that the formatting of the description is important
- Class EvenDescription could very well be a foaf:Document, which is broad enough.
- Web page or PDF information could be modelled as foaf:Document with specific relationship with Event, like cpev:description, or with a general property like foaf:page.

Further discussions on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to:

1) keep description property as Text (so it can be used for multilanguage)
2) to replace the property "URL" with "homepage" (which has more meaning) pointing to a foaf:Document where more detailed or structured description could be kept

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Keep description.
- Replace url (URI) with homepage (Document).
- Keep registration (Document).
- Add eventNumber.
